### ISSUE TITLE
I2C Pi to Arduino Communication

### ISSUE THREAD

**Issue by MachineSaver** [Spuriosity1/basilbot#3]
Hello,
I followed you over from a post on stackoverflow.
It seems you got around the problem of sending data from arduino back to a raspberrypi.
Can you point me to the files that minimally allowed you to do this?
Much appreciated.

**Comment by Spuriosity1** [comment]
Hi there,

The relevant files are found at 
Arduino: https://github.com/Spuriosity1/basilbot/blob/dev/sketches/plant-I2C/src/plantI2C.ino <https://github.com/Spuriosity1/basilbot/tree/dev/sketches/plant-I2C-v2/src>
Pi: https://github.com/Spuriosity1/basilbot/blob/dev/libbasil_I2C.py <https://github.com/Spuriosity1/basilbot/blob/dev/libbasil_I2C.py>

I’m not sure how old my SO answer is, but at one point I changed everything to communicate over I2C instead of the USB serial port, which avoided some unfortunate edge cases when multiple requests to the Arduino were made in rapid succession. Rather than deal with the bug in the smbus2 library that made it impossible to use read_i2c_block_data (this may have been fixed by now, probably not), I just used single byte sized I2C reads via read_byte.

The documentation is abysmal, but written concisely:
The general idea is that the Arduino has an internal buffer and a pointer to an element of that buffer. The pre-measurement M command manipulates the position of the pointer, while the asynchronous requestEvent function returns the byte pointed to.

Please feel free to contact me for further explanation.

Kind regards,
Alaric
